all:
  children:
    lab:
      children:
        control:
          hosts:
            control-01:
              ansible_host: 172.24.3.51
              ansible_user: ansible
        automation_targets:
          hosts:
            git-01:
              ansible_host: 172.24.3.52
              ansible_user: automation
            docker-01:
              ansible_host: 172.24.3.53
              ansible_user: automation
            siem-01:
              ansible_host: 172.24.3.55
              ansible_user: automation
        windows:
          hosts:
            dc-01:
              ansible_host: 172.24.3.54
              ansible_user: Administrator
              ansible_connection: winrm
              ansible_winrm_transport: basic
